<H2>MM03_B09705039_劉惟恩

In [1]:
import numpy as np

<H3>Question 1

<H4>(a)<br>
purpose: generate six sentences<br>
result: create six string data

In [2]:
A = "I love Management Mathematics"
B = "I hate Management Mathematics"
C = "I love Operations Research"
D = "I hate Operations Research"
E = "I love data mining"
F = "I hate data mining"

<H4>(b)<br>
purpose: split all six sentences and convert them into lowercase<br>
result: create six string lists with words in lowercase

In [3]:
wordsA = A.lower().split()
wordsB = B.lower().split()
wordsC = C.lower().split()
wordsD = D.lower().split()
wordsE = E.lower().split()
wordsF = F.lower().split()

for i in wordsA, wordsB, wordsC, wordsD, wordsE, wordsF:
    print(i)

['i', 'love', 'management', 'mathematics']
['i', 'hate', 'management', 'mathematics']
['i', 'love', 'operations', 'research']
['i', 'hate', 'operations', 'research']
['i', 'love', 'data', 'mining']
['i', 'hate', 'data', 'mining']


<h4>(c)<br>
purpose: identify the dimensionality of the feature space and print all vocabulary<br>
result: create a set of different vocabulary

In [4]:
vocab = set(wordsA)

for i in wordsA, wordsB, wordsC, wordsD, wordsE, wordsF:
    vocab = vocab.union(set(i))

print(vocab)

{'love', 'operations', 'mining', 'mathematics', 'data', 'research', 'hate', 'i', 'management'}


<h4>(d)<br>
purpose: build the one to one mapping between features and IDs in the feature space<br>
result: convert vocab in to a list

In [5]:
vocab = list(vocab)
print(vocab)

['love', 'operations', 'mining', 'mathematics', 'data', 'research', 'hate', 'i', 'management']


<h4>(e)<br>
purpose: declare six 1D arrays for the six sentences and build each word vector by increasing the corresponding feature value<br>
result: create six vectors of each sentence

In [6]:
vA = np.zeros(len(vocab), dtype=float)
vB = np.zeros(len(vocab), dtype=float)
vC = np.zeros(len(vocab), dtype=float)
vD = np.zeros(len(vocab), dtype=float)
vE = np.zeros(len(vocab), dtype=float)
vF = np.zeros(len(vocab), dtype=float)

for i, j in zip((wordsA, wordsB, wordsC, wordsD, wordsE, wordsF), (vA, vB, vC, vD, vE, vF)):
    for w in i:
        i = vocab.index(w)
        j[i] += 1
    
for i in vA, vB, vC, vD, vE, vF:
    print(i)

[1. 0. 0. 1. 0. 0. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 1. 1.]
[1. 1. 0. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 0. 0. 1. 1. 1. 0.]
[1. 0. 1. 0. 1. 0. 0. 1. 0.]
[0. 0. 1. 0. 1. 0. 1. 1. 0.]


<h4>(f)<br>
purpose: compute the cosine similarity between two vectors, and show a 6*6 matrix including these similarity values<br>
result: create a 6*6 matrix of all cosine values

In [7]:
sol_matrix = np.eye(6)
num_i = -1
for i in vA, vB, vC, vD, vE, vF:
    num_i += 1
    num_j = -1
    for j in vA, vB, vC, vD, vE, vF:
        num_j += 1
        cos = np.dot(i, j) / (np.sqrt(np.dot(i,i)) * np.sqrt(np.dot(j,j)))
        sol_matrix[num_i][num_j] = cos
print(sol_matrix)

[[1.   0.75 0.5  0.25 0.5  0.25]
 [0.75 1.   0.25 0.5  0.25 0.5 ]
 [0.5  0.25 1.   0.75 0.5  0.25]
 [0.25 0.5  0.75 1.   0.25 0.5 ]
 [0.5  0.25 0.5  0.25 1.   0.75]
 [0.25 0.5  0.25 0.5  0.75 1.  ]]


<h4>(g)<br>
purpose: draw results of the similarity matrix<br>
result: the similarity matrix is a symetric matrix and only has similarity values of 1, 0.25, 0.5, 0.75

<H3>Question 2

In [8]:
import math

<h4>(a)<br>
purpose: Build up the matrix, and convert all column vectors into unit vectors as matrix Q.<br>
result: Create a matrix of 8 unit vectors Q.

In [9]:
Q = np.array([[0., 6, 3, 0, 1, 0, 1, 1],
              [0, 0, 0, 0, 0, 5, 3, 2],
              [5, 4, 4, 5, 4, 0, 3, 3],
              [6, 5, 3, 3, 4, 4, 3, 2],
              [0, 0, 0, 0, 3, 0, 4, 3],
              [0, 0, 0, 0, 4, 6, 0, 2],
              [0, 0, 5, 2, 3, 3, 0, 1],
              [5, 3, 3, 2, 4, 2, 1, 1],
              [0, 0, 0, 5, 1, 3, 1, 0],
              [0, 4, 4, 3, 4, 1, 0, 3]])

for i in range(8):
    sumC = 0
    for j in range(10):
        sumC += (Q[j][i]) ** 2
    sumC = math.sqrt(sumC)
    for j in range(10):
        Q[j][i] = Q[j][i] / sumC

print(Q)

[[0.         0.59408853 0.32732684 0.         0.1        0.
  0.14744196 0.15430335]
 [0.         0.         0.         0.         0.         0.5
  0.44232587 0.3086067 ]
 [0.53916387 0.39605902 0.43643578 0.57353933 0.4        0.
  0.44232587 0.46291005]
 [0.64699664 0.49507377 0.32732684 0.3441236  0.4        0.4
  0.44232587 0.3086067 ]
 [0.         0.         0.         0.         0.3        0.
  0.58976782 0.46291005]
 [0.         0.         0.         0.         0.4        0.6
  0.         0.3086067 ]
 [0.         0.         0.54554473 0.22941573 0.3        0.3
  0.         0.15430335]
 [0.53916387 0.29704426 0.32732684 0.22941573 0.4        0.2
  0.14744196 0.15430335]
 [0.         0.         0.         0.57353933 0.1        0.3
  0.14744196 0.        ]
 [0.         0.39605902 0.43643578 0.3441236  0.4        0.1
  0.         0.46291005]]


<h4>(b)<br>
purpose: Build up an unit search vector x, entries are all 0 except for the three rows corresponding to the search rows.<br>
result: Create the unit search vector.

In [10]:
x = np.array([[1.],
              [0],
              [0],
              [1],
              [0],
              [0],
              [0],
              [1],
              [0],
              [0]])

sumA = 0
for i in range(10):
    sumA += (x[i][0]) ** 2
sumA = math.sqrt(sumA)
for i in range(10):
    x[i][0] = x[i][0] / sumA
    
print(x)

[[0.57735027]
 [0.        ]
 [0.        ]
 [0.57735027]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.57735027]
 [0.        ]
 [0.        ]]


<h4>(c)<br>
purpose: Calculate the cosine similarity and rank the modules.<br>
result: Create a vector of cosine similarity and rank the similarity of the modules.

In [11]:
y = np.dot(Q.T, x)
print(y)

sort = np.zeros((1, 8))
for i in range(8):
    maxNum = -1
    now = 0.0
    for j in range(8):
        if y[j][0] >= now:
            maxNum = j
            now = y[j][0]
    sort[0][i] = maxNum
    y[maxNum][0] = 0
            
print("Rank:")
for i in range(8):
    print("%d : M%d" %(i + 1 ,sort[0][i] + 1))

[[0.68483009]
 [0.80032673]
 [0.56694671]
 [0.33113309]
 [0.51961524]
 [0.34641016]
 [0.42562827]
 [0.35634832]]
Rank:
1 : M2
2 : M1
3 : M3
4 : M5
5 : M7
6 : M8
7 : M6
8 : M4
